# Generated by Django 5.1.2 on 2024-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipojustificacion', '0014_auto_20200203_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltipojustificacion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tipo justificacion', 'verbose_name_plural': 'historical tipo justificacions'},
        ),
        migrations.AlterField(
            model_name='historicaltipojustificacion',
            name='cargo',
            field=models.CharField(blank=True, choices=[], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltipojustificacion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tipojustificacion',
            name='cargo',
            field=models.CharField(blank=True, choices=[], max_length=20),
        ),
    ]
