# Generated by Django 5.1.2 on 2024-11-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipojustificacion', '0015_alter_historicaltipojustificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltipojustificacion',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipojustificacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
