# Generated by Django 5.1.2 on 2024-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0002_auto_20200203_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaljustificacion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical justificacion', 'verbose_name_plural': 'historical justificacions'},
        ),
        migrations.AlterField(
            model_name='historicaljustificacion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
