# Generated by Django 5.1.2 on 2024-11-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0005_remove_cargoscache_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoscache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
