# Generated by Django 5.1.2 on 2024-11-12 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_customuser_id_alter_historicalcustomuser_id'),
        ('mensajeria', '0003_alter_historicaltelefono_id_alter_telefono_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mensajeria.telefono'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='telefono',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mensajeria.telefono'),
        ),
    ]
