# Generated by Django 5.1.2 on 2024-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalasistencia',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical asistencia', 'verbose_name_plural': 'historical asistencias'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='condicion',
            field=models.CharField(choices=[('Asistencia', 'Asistencia'), ('Inasistencia Injustificada', 'Inasistencia Injustificada'), ('Inasistencia Justificada', 'Inasistencia Justificada'), ('Inconsistencia Marcaje', 'Inconsistencia Marcaje'), ('Correccion Inconsistencia', 'Correccion Inconsistencia'), ('Anulacion por Marcaje', 'Anulacion por Marcaje')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='condicion',
            field=models.CharField(choices=[('Asistencia', 'Asistencia'), ('Inasistencia Injustificada', 'Inasistencia Injustificada'), ('Inasistencia Justificada', 'Inasistencia Justificada'), ('Inconsistencia Marcaje', 'Inconsistencia Marcaje'), ('Correccion Inconsistencia', 'Correccion Inconsistencia'), ('Anulacion por Marcaje', 'Anulacion por Marcaje')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
